### PR TITLE
Focal point support

### PR DESCRIPTION
**Pull request by EdgarPost**
Implemented focal point support request: https://github.com/Intervention/image/issues/327

### CODE REVIEW

**Comment by localheinz** [comment]
Blocked by #491.

**Comment by mediamonks-robert** [comment]
+1 on this

**Comment by JCMais** [comment]
What is the status on this PR?

**Comment by mediamonks-robert** [comment]
So, was this merged then? Any feedback would be useful.

**Comment by olivervogel** [comment]
Sorry, I don't like how the position is squeezed in as string. You can always create your own custom commands as [filters](http://image.intervention.io/use/filters).

**Pull request closed without merging**
