### PR TITLE
Add HEIC support

### PR DESCRIPTION
**Pull request by it-can**

### CODE REVIEW

**Comment by it-can** [comment]
@olivervogel could you take a look at this pr?

**Comment by xlcrr** [comment]
Hi, I am running 2.6.1 locally but this code doesn't show up in my AbstractEncoder.php

Was the version number not updated after this PR?

**Comment by it-can** [comment]
> Hi, I am running 2.6.1 locally but this code doesn't show up in my AbstractEncoder.php
> 
> Was the version number not updated after this PR?

There is no new tag yet @olivervogel

**Comment by johnkary** [comment]
This feature is only available via version >= 2.7.0

**Comment by Darkethic06** [comment]
see #1230

**Pull request merged**
