### PR TITLE
 Bugfix (Encoding format (tmp) is not supported)

### PR DESCRIPTION
**Pull request by vladrub**
For Windows OS

### CODE REVIEW

**Comment by benjamindoe** [comment]
What's a "tmp" format in terms of images?

**Comment by olivervogel** [comment]
Can you elaborate, when this error occurs?

**Comment by eNzyOfficial** [comment]
Are we able to get this merged? Having the same problem going from linux to windows. Works fine on linux but getting `Encoding format (tmp) is not supported.` on windows.

**Comment by eNzyOfficial** [comment]
Are we able to get this merged? Having the same problem going from linux to windows. Works fine on linux but getting `Encoding format (tmp) is not supported.` on windows. @olivervogel

**Pull request closed without merging**
