### PR TITLE
Support for Webp

### PR DESCRIPTION
**Pull request by thomas4Bitcraft**

### CODE REVIEW

**Comment by thomas4Bitcraft** [comment]
I noticed that on some systems converting images to webp does not work. So i fixed the processWebp function according to this:
https://stackoverflow.com/questions/39292617/fatal-error-paletter-image-not-supported-by-webp

**Comment by Equruler** [comment]
Please merge this request.

**Comment by thomas4Bitcraft** [comment]
i don't have write access to this repo

**Comment by thomas4Bitcraft** [comment]
@Equruler is it possible that someone merges this? Then i can use this project again and not my own fork

**Comment by Bakoro** [comment]
Hello ! I have problem with paletter error and this merge could fix. Please, can you merge ?

**Comment by thomas4Bitcraft** [comment]
@Bakoro  i wanted to - but its not in my power to do that

**Comment by tanvir-retailai** [comment]
This is a nice fix. is there anyone from original team would like to consider the solution which @thomas4Bitcraft proposed here.

**Pull request merged**
