### PR TITLE
fixed Image::encode() leaks memory

### PR DESCRIPTION
**Pull request by olivervogel**

### CODE REVIEW

**Comment by tinpont** [comment]
This may affect who wants save multi size of same image.

**Comment by olivervogel** [comment]
Can you explain? Maybe with a code example.

**Comment by tinpont** [comment]
Before this commit, I could save avatar like this:
```php
     foreach ([128, 64] as $size) {
            $avatarFile = str_replace('{size}', $size, $pathName);
            $image->widen($size)->save($avatarPath . $avatarFile);
    }
```

After this commit, maybe I just can:
```php
   $image->backup();
   foreach ([128, 64] as $size) {
       $image->reset();

       $avatarFile = str_replace('{size}', $size, $pathName);
       $content = $image->widen($size)->save($avatarPath . $avatarFile);
   }
   $image->destroy();
```

**Comment by olivervogel** [comment]
Thanks, I look into it.

**Pull request merged**
