### PR TITLE
Add webp support for GD driver

### PR DESCRIPTION
**Pull request by conroyp**
[`imagewebp`](http://php.net/manual/en/function.imagewebp.php) was added in php 5.5, so add webp support for the GD driver (handles half of https://github.com/Intervention/image/issues/233).

There's a bit more code here than one might initially expect, as while webp support is now technically in GD, the way it's been implemented seems to be a little inconsistent in parts. So while processing functions like `imagewebp` and `imagecreatefromwebp` exist, there is no `IMAGETYPE_WEBP` constant, so functions like `image_type_to_mime_type` and `getimagesize` don't work as smoothly as with more traditional image types. Mime type detection reports a webp image as `application/octet-stream`. So we have to override the mime type to `image/webp` when we have `application/octet-stream` and either have loaded the image so recognise the webp [magic bytes](https://developers.google.com/speed/webp/docs/riff_container#webp_file_header) at the start of the file, or fall back to file extension checking.

### CODE REVIEW

**Comment by olivervogel** [comment]
Thank you. Will be included in the next release.

**Comment by pierrejoye** [comment]
Hm, you have a good point. These constants are not all in GD and the mime functions neither.

I will see what I can do get them updated in 5.5+. Idea being to centralized all that in 7.

**Comment by pfbernardo** [comment]
Hi guys,

thanks for this amazing library. Quick question:

what is the release date for the next version and will it include this code?

Thanks.

**Comment by garygreen** [comment]
Any news on when PR will be merged?

**Comment by garygreen** [comment]
@conroyp is it possible to support webp in ImageMagik? Should be easier than gd....?

**Comment by olivervogel** [comment]
See https://github.com/Intervention/image/issues/233

**Pull request closed without merging**
