### PR TITLE
Adds PHP 7.4 to the Travis build

### PR DESCRIPTION
**Pull request by freshleafmedia**
Currently the Travis build doesn't build in a PHP 7.4 environment, this PR adds it

### CODE REVIEW

**Comment by mfn** [comment]
Unfortunately the build fails => https://travis-ci.org/github/Intervention/image/jobs/743232294

**Comment by mfn** [comment]
I can't make sense of the travis builds at https://travis-ci.org/github/Intervention/image/pull_requests
image

The second one, the red one is at https://travis-ci.org/github/Intervention/image/builds/743906607 and is red
image

The first one is green at https://travis-ci.org/github/Intervention/image/builds/743912386
image

But this is now showing any other jobs and seems to be only a single test of the matrix?

Also the referenced commit hashes don't align with any here. No idea, it confuses me.

Apologies if I got something wrong here.

**Comment by freshleafmedia** [comment]
@mfn I had to mess with the Travis config to get it to run the earlier version of PHP on an older version of Ubuntu.

If you look now you will see all the tests pass

**Review by mfn — APPROVED** [review]
Nice, great (and daunting!) job ;)

https://travis-ci.org/github/Intervention/image/builds/743949277 LGTM!

(Note: I'm not the maintainer and can't merge!)

**Comment by mfn** [comment]
> Also the referenced commit hashes don't align with any here. No idea, it confuses me.

Btw, I think I figured out this one: when performing the tests, since this is based on pull requests, travis actually performs a merge commit and then tests this commit, ensuring the tests of this PR don't just work in isolation but actually once merged into master.

**Pull request merged**
