### PR TITLE
Allow EXIF data to be read from streams.  Fixes: #1190

### PR DESCRIPTION
**Pull request by fisharebest**
Intervention can create images from filenames and streams (and others).

PHP:exif_read_data() can read EXIF data from both filenames and streams (since PHP 7.2).

But when intervention creates an `Image` from a stream, it reads the data (excluding the EXIF data), and then creates a new stream from just the image data.  Thus the EXIF data is lost.

We lose the original stream (and the EXIF data) here: [src/Intervention/Image/AbstractDecoder.php#L125](https://github.com/Intervention/image/blob/54934ae8ea3661fd189437df90fb09ec3b679c74/src/Intervention/Image/AbstractDecoder.php#L125)

We create a new stream from this (EXIF-less) data here: [src/Intervention/Image/Commands/StreamCommand.php#L20](https://github.com/Intervention/image/blob/54934ae8ea3661fd189437df90fb09ec3b679c74/src/Intervention/Image/Commands/StreamCommand.php#L20)

When we create an image from a file, we store the basename/dirname in the `Image` object.  (Actually, in the parent `File` object).  This original data is used to read EXIF data.

This PR uses a similar approach for images created from a `stream`.  We keep a copy of the original stream and use it when we need the EXIF data. 

I created a test case for this, using a rotated image.  This test passes.  There are a number of pre-existing test failures, which I haven't investigated.

### CODE REVIEW

**Comment by fisharebest** [comment]
Note: I left the existing `->stream()->detach()` code in place.

I don't think it works, but it is possible it may work with custom drivers.

**Review by thomaspicquet — APPROVED** [review]

**Comment by Samvdg** [comment]
@fisharebest Do you still use this package? I'm currently looking for an alternative because of the EXIF data issue and was wondering what you use if it's not this

**Comment by fisharebest** [comment]
> Do you still use this package? I'm currently looking for an alternative because of the EXIF data issue and was wondering what you use if it's not this

I use my own fork of this package, with this fix.

**Comment by Samvdg** [comment]
> > Do you still use this package? I'm currently looking for an alternative because of the EXIF data issue and was wondering what you use if it's not this
> 
> I use my own fork of this package, with this fix.

Thanks for the reply! I ended up writing my own middleware for the package. Now the issue should be fixed though

**Pull request closed without merging**
